### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/unix-time#45]
@sighingnow 

I'm currently working on `fast-logger` to relay on `unix-time` only even on Windows. Unfortunately, it appeared that `unix-time-0.4.0` on *Hackage* cannot be compilied on Windows:

https://ci.appveyor.com/project/kazu-yamamoto/logger/builds/21082179

I quickly added `win_patch.h` to `unix-time.cabal` and released `unix-time-0.4.1`. But it cannot be complied, either:

https://ci.appveyor.com/project/kazu-yamamoto/unix-time/builds/21082166

I have no idea why this happens at this moment.

**Comment by sighingnow** [comment]
From the log I see that the failure [builds/21082179](https://ci.appveyor.com/project/kazu-yamamoto/logger/builds/210821790) is built against unix-time-0.4.1, rather than 0.4.0.

https://ci.appveyor.com/project/kazu-yamamoto/logger/builds/21082179#L248

Could you please show me the failure with unix-time-0.4.0 ?

**Comment by sighingnow** [comment]
Fixed in #46.
